version: "3"
services:
  clickhouse:
    image: yandex/clickhouse-server
    volumes:
#      - ./docker/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9000:9000"
      - "8123:8123"
#  docker run -it -p 9000:9000 -p 9009:9009 -p 8123:8123 --volume "./docker/users.xml:/etc/clickhouse-server/users.xml" --platform linux/amd64 --ulimit nofile=262144:262144 clickhouse/clickhouse-server